import matplotlib.pyplot as plt
from scipy.special import logit
from scipy.stats.stats import pearsonr
import sys

# USAGE:
# interpret and plot the results generated by predictor_tables


def select(table, column):
    return [row[column] for row in table]


header = sys.stdin.readline()[:-1].split()[1:]
table = []
while True:
    row = sys.stdin.readline()[:-1].split(",")
    if not row:
        break
    word_info, probs = row[:3], map(float, row[3:])

    if any(map(lambda x: x == 0, probs)):
        print >>sys.stderr, "Error in word", word_info[1:3], probs

    table.append(probs)


def plot(x, y, xlabel, ylabel, title):
    plt.close()
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.scatter(x, y, alpha=0.2)
    plt.title(title)
    print pearsonr(x, y)[0]
    plt.show()


def logit_plot(x, y, xlabel, ylabel, title):
    plot(logit(x), logit(y), "logit " + xlabel, "logit " + ylabel, title)


n = len(header)
for i in xrange(1, n):
    name = header[0]
    name2 = header[i]

    cloze_prob, prob = select(table, 0), select(table, i)

    logit_plot(cloze_prob, prob, name, name2, "probabilities")
