import matplotlib.pyplot as plt
from scipy.special import logit
from scipy.stats.stats import pearsonr
import sys
import io
import numpy as np

# USAGE:
# interpret and plot the results generated by predictor_tables


def select(table, column):
    return [row[column] for row in table]


def plot(x, y, xlabel, ylabel, title):
    plt.close()
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.scatter(x, y, alpha=0.2)

    p = np.poly1d(np.polyfit(x, y, 1))
    xx = np.linspace(min(x), max(x), num=100)

    plt.plot(xx, p(xx), "r-")

    plt.title(title)
    print pearsonr(x, y)[0]
    plt.show()


def logit_plot(x, y, xlabel, ylabel, title):
    plot(logit(x), logit(y), "logit " + xlabel, "logit " + ylabel, title)

if __name__ == "__main__":
    stdin = io.open(sys.stdin.fileno(), "r", encoding="utf-8")

    header = stdin.readline()[:-1].split(",")

    table = []

    while True:
        line = stdin.readline()[:-1]
        if not line:
            break
        row = line.split(",")
        if not row:
            break
        probs = map(float, row)

        table.append(probs)
    n = len(header)
    for i in xrange(1, n):
        name = header[0]
        name2 = header[i]

        cloze_prob, prob = select(table, 0), select(table, i)

        logit_plot(cloze_prob, prob, name, name2, "probabilities")
